const projectsData = [
    {
        title: "Phobophobia",
        slug: "phobophobia",
        banner: "assets/images/phobophobia/banner.jpg",
        blurb: "A story-driven puzzle game about conquering fears and helping others in a new town.",
        genre: "Puzzle Adventure",
        type: "University",
        tags: ["2D", "Artist", "GameMaker", "Programmer"],
        dataTags: "2D Artist GameMaker Programmer",
        date: "2024-01-01",
        status: "Completed",
        duration: "Jan 2024 - Jun 2024",
        engine: "GameMaker",
        language: "GML",
        teamSize: "4",
        role: "Programmer, Artist",
        platform: "PC (Windows)",
        youtubeId: "",
        githubLink: "",
        itchLink: "https://greenygamedev.itch.io",
        gddLink: "",
        techIcons: ["gamemaker.png"]
    },
    {
        title: "Revenge of the Renter",
        slug: "revenge-of-the-renter",
        banner: "assets/images/revenge-of-the-renter/banner.jpg",
        blurb: "A stealth-puzzle game about holding your slumlord accountable and saving energy.",
        genre: "Stealth Puzzle",
        type: "University",
        tags: ["3D", "Artist", "Programmer", "Unity"],
        dataTags: "3D Artist Programmer Unity",
        date: "2024-02-01",
        status: "Completed",
        duration: "Jan 2024 - Jun 2024",
        engine: "Unity",
        language: "C#",
        teamSize: "3",
        role: "Programmer",
        platform: "PC (Windows)",
        youtubeId: "",
        githubLink: "",
        itchLink: "https://greenygamedev.itch.io",
        gddLink: "",
        techIcons: ["unity.svg", "c-sharp.png"]
    },
    {
        title: "Mech Mates",
        slug: "mechmates",
        banner: "assets/images/mechmates/banner.jpg",
        blurb: "A local co-op arcade shooter where you and a friend blast as many aliens as possible.",
        genre: "Co-op Arcade Shooter",
        type: "GameJam",
        tags: ["3D", "Programmer", "Unity"],
        dataTags: "3D Programmer Unity",
        date: "2024-03-01",
        status: "Completed",
        duration: "Jan 2024",
        engine: "Unity",
        language: "C#",
        teamSize: "5",
        role: "Programmer",
        platform: "PC (Windows)",
        youtubeId: "",
        githubLink: "",
        itchLink: "https://greenygamedev.itch.io",
        gddLink: "",
        techIcons: ["unity.svg", "c-sharp.png"]
    },
    {
        title: "The News",
        slug: "the-news",
        banner: "assets/images/the-news/banner.jpg",
        blurb: "A VR game about managing a chaotic news broadcast 30 years in the future.",
        genre: "VR Simulation",
        type: "University",
        tags: ["3D", "Artist", "Programmer", "Unity", "VR"],
        dataTags: "3D Artist Programmer Unity VR",
        date: "2024-04-01",
        status: "Completed",
        duration: "Jan 2024 - Jun 2024",
        engine: "Unity",
        language: "C#",
        teamSize: "4",
        role: "Programmer",
        platform: "VR",
        youtubeId: "",
        githubLink: "",
        itchLink: "https://greenygamedev.itch.io",
        gddLink: "",
        techIcons: ["unity.svg", "c-sharp.png"]
    },
    {
        title: "Levelling & Skill Tree",
        slug: "skill-tree",
        banner: "assets/images/skill-tree/banner.jpg",
        blurb: "A scalable levelling system and skill tree implemented with game-design patterns.",
        genre: "System Architecture",
        type: "University",
        tags: ["3D", "Programmer", "Unity"],
        dataTags: "3D Programmer Unity",
        date: "2024-05-01",
        status: "Completed",
        duration: "Jan 2024 - Jun 2024",
        engine: "Unity",
        language: "C#",
        teamSize: "1",
        role: "Programmer",
        platform: "PC (Windows)",
        youtubeId: "",
        githubLink: "",
        itchLink: "https://greenygamedev.itch.io",
        gddLink: "",
        techIcons: ["unity.svg", "c-sharp.png"]
    },
    {
        title: "Noorderpoort Escape",
        slug: "noorderpoort",
        banner: "assets/images/noorderpoort/banner.jpg",
        blurb: "A VR escape-room experience about digital citizenship for a real-world client.",
        genre: "VR Educational Experience",
        type: "Client",
        tags: ["3D", "Artist", "GameDesigner", "Programmer", "Unity", "VR"],
        dataTags: "3D Artist GameDesigner Programmer Unity VR",
        date: "2025-01-01",
        status: "Completed",
        duration: "Aug 2024 - Jan 2025",
        engine: "Unity",
        language: "C#",
        teamSize: "5",
        role: "Programmer, Designer",
        platform: "VR",
        youtubeId: "",
        githubLink: "",
        itchLink: "https://greenygamedev.itch.io",
        gddLink: "",
        techIcons: ["unity.svg", "c-sharp.png"]
    },
    {
        title: "Project Parasite",
        slug: "project-parasite",
        banner: "assets/images/project-parasite/banner.jpg",
        blurb: "A reverse-horror game where you play as a parasite that infects defenceless hosts in a top-secret government facility.",
        genre: "Reverse Horror",
        type: "Personal",
        tags: ["3D", "Artist", "GameDesigner", "Programmer", "Unity"],
        dataTags: "3D Artist GameDesigner Programmer Unity",
        date: "2026-01-01",
        status: "Ongoing",
        duration: "8 Aug 2024 - 31 Jan 2025",
        engine: "Unity",
        language: "C#",
        teamSize: "1",
        role: "Programmer, Designer",
        platform: "PC (Windows)",
        youtubeId: "_YRjZhuRAcs",
        githubLink: "",
        itchLink: "https://greenygamedev.itch.io",
        gddLink: "assets/images/project-parasite/Project-Parasite_GDD.pdf",
        techIcons: ["unity.svg", "c-sharp.png", "blender.png", "photoshop.png", "artstation.svg"]
    },
    {
        title: "(Dis)Obey Me",
        slug: "disobey-me",
        banner: "assets/images/disobey-me/banner.jpg",
        blurb: "A puzzle game about defying your creators orders.",
        genre: "Puzzle Game",
        type: "GameJam",
        tags: ["3D", "Artist", "GameDesigner", "Programmer", "Unity"],
        dataTags: "3D Artist GameDesigner Programmer Unity",
        date: "2025-07-30",
        status: "Completed",
        duration: "30 July 2025 - 3 Aug 2025",
        engine: "Unity",
        language: "C#",
        teamSize: "6",
        role: "Programmer",
        platform: "PC (Windows)",
        youtubeId: "",
        githubLink: "",
        itchLink: "https://greenygamedev.itch.io",
        gddLink: "",
        techIcons: ["unity.svg", "c-sharp.png"]
    }
];

// Sort newest to oldest using localeCompare for robust date string comparison
export const projects = [...projectsData].sort((a, b) => b.date.localeCompare(a.date));
